(defvar task-dir "~/Dropbox/RoamNotes/Tasks.org")
(setq org-directory "~/Dropbox/RoamNotes")
(defvar user-bin-path "/Users/pengyo/bin/")
(defvar user-common-bin-path ":/Users/pengyo/bin/")
(defvar mmdc-path "/opt/homebrew/bin/mmdc")
(defvar revealjs-path "file:///Volumes/Samsung_T5/github/reveal-ppt/reveal.js")
(provide 'init-var)
