;;; Automatically generated by ‘recentf’ on Sat Apr  8 20:53:51 2023.

(setq recentf-list
      '(
        "/Volumes/Samsung_T5/Document/RoamNotes/Tasks.org_archive"
        "/Volumes/Samsung_T5/Document/RoamNotes/Tasks.org"
        "/Users/pengyo/.emacs.d/lisp/init-dired.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
