;;; Automatically generated by ‘recentf’ on Sun Apr  9 17:01:30 2023.

(setq recentf-list
      '(
        "/Volumes/Samsung_T5/Document/RoamNotes/Tasks.org_archive"
        "/Volumes/Samsung_T5/Document/RoamNotes/Tasks.org"
        "/Users/pengyo/.emacs.d/site-lisp/advance-words-count.el"
        "/Users/pengyo/.dotfiles/.emacs.d/lisp/init-key.el"
        "/Users/pengyo/.emacs.d/lisp/init-key.el"
        "/Users/pengyo/.dotfiles/.emacs.d/lisp/init-utility.el"
        #("/Volumes/Samsung_T5/Document/Paper/topics.org" 0 45 (match-part "/Volumes/Samsung_T5/Document/Paper/topics.org"))
        "/Users/pengyo/.dotfiles/.emacs.d/custom.el"
        "/Users/pengyo/.dotfiles/.emacs.d/lisp/init-fun.el"
        "/Users/pengyo/.dotfiles/.emacs.d/lisp/init-ui.el"
        "/Users/pengyo/.dotfiles/.emacs.d/init.el"
        "/Users/pengyo/.emacs.d/init.el"
        "/Users/pengyo/.dotfiles/.emacs.d/lisp/init-dired.el"
        "/Users/pengyo/.emacs.d/lisp/init-dired.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
